// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/pyroscopex/config.proto

package pyroscopex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for Pyroscope continuous profiling
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fraction of mutex contention events reported, 1 means all events are reported
	MutexProfileRate *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=mutex_profile_rate,json=mutexProfileRate,proto3" json:"mutex_profile_rate,omitempty"`
	// Fraction of blocking events reported, in nanoseconds
	BlockProfileRate *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=block_profile_rate,json=blockProfileRate,proto3" json:"block_profile_rate,omitempty"`
	// Name of the application that will be displayed in Pyroscope UI
	AppName *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Tags to attach to the profiling data, key-value pairs
	Tags map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Address of the Pyroscope server to send profiling data to
	ServerAddr *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	// HTTP basic authentication username
	BasicAuthUser *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=basic_auth_user,json=basicAuthUser,proto3" json:"basic_auth_user,omitempty"` // http basic auth user
	// HTTP basic authentication password
	BasicAuthPassword *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=basic_auth_password,json=basicAuthPassword,proto3" json:"basic_auth_password,omitempty"` // http basic auth password
	// Tenant ID for multi-tenant Pyroscope installations
	TenantId *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // specify TenantId when using phlare multi-tenancy
	// How frequently profiling data should be uploaded to the server
	UploadRate *durationpb.Duration `protobuf:"bytes,9,opt,name=upload_rate,json=uploadRate,proto3" json:"upload_rate,omitempty"`
	// List of profile types to collect (e.g., cpu, mem, goroutines, etc.)
	ProfileTypes []string `protobuf:"bytes,10,rep,name=profile_types,json=profileTypes,proto3" json:"profile_types,omitempty"`
	// When true, disables automatic garbage collection runs between heap profile collections
	DisableGcRuns *wrapperspb.BoolValue `protobuf:"bytes,11,opt,name=disable_gc_runs,json=disableGcRuns,proto3" json:"disable_gc_runs,omitempty"` // this will disable automatic runtime.GC runs between getting the heap profiles
	// Additional HTTP headers to send with requests to the Pyroscope server
	HttpHeaders   map[string]string `protobuf:"bytes,12,rep,name=http_headers,json=httpHeaders,proto3" json:"http_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_pyroscopex_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pyroscopex_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_pyroscopex_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetMutexProfileRate() *wrapperspb.Int32Value {
	if x != nil {
		return x.MutexProfileRate
	}
	return nil
}

func (x *Config) GetBlockProfileRate() *wrapperspb.Int32Value {
	if x != nil {
		return x.BlockProfileRate
	}
	return nil
}

func (x *Config) GetAppName() *wrapperspb.StringValue {
	if x != nil {
		return x.AppName
	}
	return nil
}

func (x *Config) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Config) GetServerAddr() *wrapperspb.StringValue {
	if x != nil {
		return x.ServerAddr
	}
	return nil
}

func (x *Config) GetBasicAuthUser() *wrapperspb.StringValue {
	if x != nil {
		return x.BasicAuthUser
	}
	return nil
}

func (x *Config) GetBasicAuthPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.BasicAuthPassword
	}
	return nil
}

func (x *Config) GetTenantId() *wrapperspb.StringValue {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *Config) GetUploadRate() *durationpb.Duration {
	if x != nil {
		return x.UploadRate
	}
	return nil
}

func (x *Config) GetProfileTypes() []string {
	if x != nil {
		return x.ProfileTypes
	}
	return nil
}

func (x *Config) GetDisableGcRuns() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableGcRuns
	}
	return nil
}

func (x *Config) GetHttpHeaders() map[string]string {
	if x != nil {
		return x.HttpHeaders
	}
	return nil
}

var File_pkg_pyroscopex_config_proto protoreflect.FileDescriptor

const file_pkg_pyroscopex_config_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/pyroscopex/config.proto\x12\x15grocer.pkg.pyroscopex\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x93\a\n" +
	"\x06Config\x12I\n" +
	"\x12mutex_profile_rate\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x10mutexProfileRate\x12I\n" +
	"\x12block_profile_rate\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x10blockProfileRate\x127\n" +
	"\bapp_name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\aappName\x12;\n" +
	"\x04tags\x18\x04 \x03(\v2'.grocer.pkg.pyroscopex.Config.TagsEntryR\x04tags\x12=\n" +
	"\vserver_addr\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"serverAddr\x12D\n" +
	"\x0fbasic_auth_user\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\rbasicAuthUser\x12L\n" +
	"\x13basic_auth_password\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x11basicAuthPassword\x129\n" +
	"\ttenant_id\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\btenantId\x12:\n" +
	"\vupload_rate\x18\t \x01(\v2\x19.google.protobuf.DurationR\n" +
	"uploadRate\x12#\n" +
	"\rprofile_types\x18\n" +
	" \x03(\tR\fprofileTypes\x12B\n" +
	"\x0fdisable_gc_runs\x18\v \x01(\v2\x1a.google.protobuf.BoolValueR\rdisableGcRuns\x12Q\n" +
	"\fhttp_headers\x18\f \x03(\v2..grocer.pkg.pyroscopex.Config.HttpHeadersEntryR\vhttpHeaders\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10HttpHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B5Z3github.com/soyacen/grocer/pkg/pyroscopex;pyroscopexb\x06proto3"

var (
	file_pkg_pyroscopex_config_proto_rawDescOnce sync.Once
	file_pkg_pyroscopex_config_proto_rawDescData []byte
)

func file_pkg_pyroscopex_config_proto_rawDescGZIP() []byte {
	file_pkg_pyroscopex_config_proto_rawDescOnce.Do(func() {
		file_pkg_pyroscopex_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pyroscopex_config_proto_rawDesc), len(file_pkg_pyroscopex_config_proto_rawDesc)))
	})
	return file_pkg_pyroscopex_config_proto_rawDescData
}

var file_pkg_pyroscopex_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_pyroscopex_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: grocer.pkg.pyroscopex.Config
	nil,                            // 1: grocer.pkg.pyroscopex.Config.TagsEntry
	nil,                            // 2: grocer.pkg.pyroscopex.Config.HttpHeadersEntry
	(*wrapperspb.Int32Value)(nil),  // 3: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*durationpb.Duration)(nil),    // 5: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),   // 6: google.protobuf.BoolValue
}
var file_pkg_pyroscopex_config_proto_depIdxs = []int32{
	3,  // 0: grocer.pkg.pyroscopex.Config.mutex_profile_rate:type_name -> google.protobuf.Int32Value
	3,  // 1: grocer.pkg.pyroscopex.Config.block_profile_rate:type_name -> google.protobuf.Int32Value
	4,  // 2: grocer.pkg.pyroscopex.Config.app_name:type_name -> google.protobuf.StringValue
	1,  // 3: grocer.pkg.pyroscopex.Config.tags:type_name -> grocer.pkg.pyroscopex.Config.TagsEntry
	4,  // 4: grocer.pkg.pyroscopex.Config.server_addr:type_name -> google.protobuf.StringValue
	4,  // 5: grocer.pkg.pyroscopex.Config.basic_auth_user:type_name -> google.protobuf.StringValue
	4,  // 6: grocer.pkg.pyroscopex.Config.basic_auth_password:type_name -> google.protobuf.StringValue
	4,  // 7: grocer.pkg.pyroscopex.Config.tenant_id:type_name -> google.protobuf.StringValue
	5,  // 8: grocer.pkg.pyroscopex.Config.upload_rate:type_name -> google.protobuf.Duration
	6,  // 9: grocer.pkg.pyroscopex.Config.disable_gc_runs:type_name -> google.protobuf.BoolValue
	2,  // 10: grocer.pkg.pyroscopex.Config.http_headers:type_name -> grocer.pkg.pyroscopex.Config.HttpHeadersEntry
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_pyroscopex_config_proto_init() }
func file_pkg_pyroscopex_config_proto_init() {
	if File_pkg_pyroscopex_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pyroscopex_config_proto_rawDesc), len(file_pkg_pyroscopex_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pyroscopex_config_proto_goTypes,
		DependencyIndexes: file_pkg_pyroscopex_config_proto_depIdxs,
		MessageInfos:      file_pkg_pyroscopex_config_proto_msgTypes,
	}.Build()
	File_pkg_pyroscopex_config_proto = out.File
	file_pkg_pyroscopex_config_proto_goTypes = nil
	file_pkg_pyroscopex_config_proto_depIdxs = nil
}
