// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grocer/jeagerx/config.proto

package jeagerx

import (
	protobufx "github.com/soyacen/grocer/grocer/protobufx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SamplingRate 采样率
	SamplingRate *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	// GRPCOptions
	GrpcOptions *GRPCOptions `protobuf:"bytes,2,opt,name=grpc_options,json=grpcOptions,proto3" json:"grpc_options,omitempty"`
	// HTTPOptions
	HttpOptions   *HTTPOptions `protobuf:"bytes,3,opt,name=http_options,json=httpOptions,proto3" json:"http_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_grocer_jeagerx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_jeagerx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_grocer_jeagerx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetSamplingRate() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SamplingRate
	}
	return nil
}

func (x *Config) GetGrpcOptions() *GRPCOptions {
	if x != nil {
		return x.GrpcOptions
	}
	return nil
}

func (x *Config) GetHttpOptions() *HTTPOptions {
	if x != nil {
		return x.HttpOptions
	}
	return nil
}

type GRPCOptions struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Endpoint           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EndpointUrl        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Insecure           *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Headers            map[string]string       `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Compressor         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=compressor,proto3" json:"compressor,omitempty"`
	ReconnectionPeriod *durationpb.Duration    `protobuf:"bytes,6,opt,name=reconnection_period,json=reconnectionPeriod,proto3" json:"reconnection_period,omitempty"`
	Timeout            *durationpb.Duration    `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ServiceConfig      *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	TlsConfig          *protobufx.TLSOptions   `protobuf:"bytes,9,opt,name=tls_config,json=tlsConfig,proto3" json:"tls_config,omitempty"`
	// GRPCConn is not directly supported in proto, handled separately
	Retry         *RetryConfig `protobuf:"bytes,10,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCOptions) Reset() {
	*x = GRPCOptions{}
	mi := &file_grocer_jeagerx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCOptions) ProtoMessage() {}

func (x *GRPCOptions) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_jeagerx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCOptions.ProtoReflect.Descriptor instead.
func (*GRPCOptions) Descriptor() ([]byte, []int) {
	return file_grocer_jeagerx_config_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCOptions) GetEndpoint() *wrapperspb.StringValue {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *GRPCOptions) GetEndpointUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.EndpointUrl
	}
	return nil
}

func (x *GRPCOptions) GetInsecure() *wrapperspb.BoolValue {
	if x != nil {
		return x.Insecure
	}
	return nil
}

func (x *GRPCOptions) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GRPCOptions) GetCompressor() *wrapperspb.StringValue {
	if x != nil {
		return x.Compressor
	}
	return nil
}

func (x *GRPCOptions) GetReconnectionPeriod() *durationpb.Duration {
	if x != nil {
		return x.ReconnectionPeriod
	}
	return nil
}

func (x *GRPCOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *GRPCOptions) GetServiceConfig() *wrapperspb.StringValue {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

func (x *GRPCOptions) GetTlsConfig() *protobufx.TLSOptions {
	if x != nil {
		return x.TlsConfig
	}
	return nil
}

func (x *GRPCOptions) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

type HTTPOptions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Endpoint      *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EndpointUrl   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Compression   *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"`
	UrlPath       *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	TlsConfig     *protobufx.TLSOptions   `protobuf:"bytes,5,opt,name=tls_config,json=tlsConfig,proto3" json:"tls_config,omitempty"`
	Insecure      *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Headers       map[string]string       `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       *durationpb.Duration    `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retry         *RetryConfig            `protobuf:"bytes,9,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPOptions) Reset() {
	*x = HTTPOptions{}
	mi := &file_grocer_jeagerx_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPOptions) ProtoMessage() {}

func (x *HTTPOptions) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_jeagerx_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPOptions.ProtoReflect.Descriptor instead.
func (*HTTPOptions) Descriptor() ([]byte, []int) {
	return file_grocer_jeagerx_config_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPOptions) GetEndpoint() *wrapperspb.StringValue {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *HTTPOptions) GetEndpointUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.EndpointUrl
	}
	return nil
}

func (x *HTTPOptions) GetCompression() *wrapperspb.Int32Value {
	if x != nil {
		return x.Compression
	}
	return nil
}

func (x *HTTPOptions) GetUrlPath() *wrapperspb.StringValue {
	if x != nil {
		return x.UrlPath
	}
	return nil
}

func (x *HTTPOptions) GetTlsConfig() *protobufx.TLSOptions {
	if x != nil {
		return x.TlsConfig
	}
	return nil
}

func (x *HTTPOptions) GetInsecure() *wrapperspb.BoolValue {
	if x != nil {
		return x.Insecure
	}
	return nil
}

func (x *HTTPOptions) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HTTPOptions) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

type RetryConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InitialInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"`
	MaxInterval     *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	MaxElapsedTime  *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_elapsed_time,json=maxElapsedTime,proto3" json:"max_elapsed_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_grocer_jeagerx_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_jeagerx_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_grocer_jeagerx_config_proto_rawDescGZIP(), []int{3}
}

func (x *RetryConfig) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *RetryConfig) GetInitialInterval() *durationpb.Duration {
	if x != nil {
		return x.InitialInterval
	}
	return nil
}

func (x *RetryConfig) GetMaxInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxInterval
	}
	return nil
}

func (x *RetryConfig) GetMaxElapsedTime() *durationpb.Duration {
	if x != nil {
		return x.MaxElapsedTime
	}
	return nil
}

var File_grocer_jeagerx_config_proto protoreflect.FileDescriptor

const file_grocer_jeagerx_config_proto_rawDesc = "" +
	"\n" +
	"\x1bgrocer/jeagerx/config.proto\x12\x0egrocer.jeagerx\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1agrocer/protobufx/tls.proto\"\xcb\x01\n" +
	"\x06Config\x12A\n" +
	"\rsampling_rate\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueR\fsamplingRate\x12>\n" +
	"\fgrpc_options\x18\x02 \x01(\v2\x1b.grocer.jeagerx.GRPCOptionsR\vgrpcOptions\x12>\n" +
	"\fhttp_options\x18\x03 \x01(\v2\x1b.grocer.jeagerx.HTTPOptionsR\vhttpOptions\"\xb4\x05\n" +
	"\vGRPCOptions\x128\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\bendpoint\x12?\n" +
	"\fendpoint_url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vendpointUrl\x126\n" +
	"\binsecure\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\binsecure\x12B\n" +
	"\aheaders\x18\x04 \x03(\v2(.grocer.jeagerx.GRPCOptions.HeadersEntryR\aheaders\x12<\n" +
	"\n" +
	"compressor\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"compressor\x12J\n" +
	"\x13reconnection_period\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x12reconnectionPeriod\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12C\n" +
	"\x0eservice_config\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\rserviceConfig\x12;\n" +
	"\n" +
	"tls_config\x18\t \x01(\v2\x1c.grocer.protobufx.TLSOptionsR\ttlsConfig\x121\n" +
	"\x05retry\x18\n" +
	" \x01(\v2\x1b.grocer.jeagerx.RetryConfigR\x05retry\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x04\n" +
	"\vHTTPOptions\x128\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\bendpoint\x12?\n" +
	"\fendpoint_url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vendpointUrl\x12=\n" +
	"\vcompression\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\vcompression\x127\n" +
	"\burl_path\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\aurlPath\x12;\n" +
	"\n" +
	"tls_config\x18\x05 \x01(\v2\x1c.grocer.protobufx.TLSOptionsR\ttlsConfig\x126\n" +
	"\binsecure\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\binsecure\x12B\n" +
	"\aheaders\x18\a \x03(\v2(.grocer.jeagerx.HTTPOptions.HeadersEntryR\aheaders\x123\n" +
	"\atimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\atimeout\x121\n" +
	"\x05retry\x18\t \x01(\v2\x1b.grocer.jeagerx.RetryConfigR\x05retry\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\vRetryConfig\x124\n" +
	"\aenabled\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\aenabled\x12D\n" +
	"\x10initial_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0finitialInterval\x12<\n" +
	"\fmax_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vmaxInterval\x12C\n" +
	"\x10max_elapsed_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0emaxElapsedTimeB2Z0github.com/soyacen/grocer/grocer/jeagerx;jeagerxb\x06proto3"

var (
	file_grocer_jeagerx_config_proto_rawDescOnce sync.Once
	file_grocer_jeagerx_config_proto_rawDescData []byte
)

func file_grocer_jeagerx_config_proto_rawDescGZIP() []byte {
	file_grocer_jeagerx_config_proto_rawDescOnce.Do(func() {
		file_grocer_jeagerx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grocer_jeagerx_config_proto_rawDesc), len(file_grocer_jeagerx_config_proto_rawDesc)))
	})
	return file_grocer_jeagerx_config_proto_rawDescData
}

var file_grocer_jeagerx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grocer_jeagerx_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: grocer.jeagerx.Config
	(*GRPCOptions)(nil),            // 1: grocer.jeagerx.GRPCOptions
	(*HTTPOptions)(nil),            // 2: grocer.jeagerx.HTTPOptions
	(*RetryConfig)(nil),            // 3: grocer.jeagerx.RetryConfig
	nil,                            // 4: grocer.jeagerx.GRPCOptions.HeadersEntry
	nil,                            // 5: grocer.jeagerx.HTTPOptions.HeadersEntry
	(*wrapperspb.DoubleValue)(nil), // 6: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 8: google.protobuf.BoolValue
	(*durationpb.Duration)(nil),    // 9: google.protobuf.Duration
	(*protobufx.TLSOptions)(nil),   // 10: grocer.protobufx.TLSOptions
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
}
var file_grocer_jeagerx_config_proto_depIdxs = []int32{
	6,  // 0: grocer.jeagerx.Config.sampling_rate:type_name -> google.protobuf.DoubleValue
	1,  // 1: grocer.jeagerx.Config.grpc_options:type_name -> grocer.jeagerx.GRPCOptions
	2,  // 2: grocer.jeagerx.Config.http_options:type_name -> grocer.jeagerx.HTTPOptions
	7,  // 3: grocer.jeagerx.GRPCOptions.endpoint:type_name -> google.protobuf.StringValue
	7,  // 4: grocer.jeagerx.GRPCOptions.endpoint_url:type_name -> google.protobuf.StringValue
	8,  // 5: grocer.jeagerx.GRPCOptions.insecure:type_name -> google.protobuf.BoolValue
	4,  // 6: grocer.jeagerx.GRPCOptions.headers:type_name -> grocer.jeagerx.GRPCOptions.HeadersEntry
	7,  // 7: grocer.jeagerx.GRPCOptions.compressor:type_name -> google.protobuf.StringValue
	9,  // 8: grocer.jeagerx.GRPCOptions.reconnection_period:type_name -> google.protobuf.Duration
	9,  // 9: grocer.jeagerx.GRPCOptions.timeout:type_name -> google.protobuf.Duration
	7,  // 10: grocer.jeagerx.GRPCOptions.service_config:type_name -> google.protobuf.StringValue
	10, // 11: grocer.jeagerx.GRPCOptions.tls_config:type_name -> grocer.protobufx.TLSOptions
	3,  // 12: grocer.jeagerx.GRPCOptions.retry:type_name -> grocer.jeagerx.RetryConfig
	7,  // 13: grocer.jeagerx.HTTPOptions.endpoint:type_name -> google.protobuf.StringValue
	7,  // 14: grocer.jeagerx.HTTPOptions.endpoint_url:type_name -> google.protobuf.StringValue
	11, // 15: grocer.jeagerx.HTTPOptions.compression:type_name -> google.protobuf.Int32Value
	7,  // 16: grocer.jeagerx.HTTPOptions.url_path:type_name -> google.protobuf.StringValue
	10, // 17: grocer.jeagerx.HTTPOptions.tls_config:type_name -> grocer.protobufx.TLSOptions
	8,  // 18: grocer.jeagerx.HTTPOptions.insecure:type_name -> google.protobuf.BoolValue
	5,  // 19: grocer.jeagerx.HTTPOptions.headers:type_name -> grocer.jeagerx.HTTPOptions.HeadersEntry
	9,  // 20: grocer.jeagerx.HTTPOptions.timeout:type_name -> google.protobuf.Duration
	3,  // 21: grocer.jeagerx.HTTPOptions.retry:type_name -> grocer.jeagerx.RetryConfig
	8,  // 22: grocer.jeagerx.RetryConfig.enabled:type_name -> google.protobuf.BoolValue
	9,  // 23: grocer.jeagerx.RetryConfig.initial_interval:type_name -> google.protobuf.Duration
	9,  // 24: grocer.jeagerx.RetryConfig.max_interval:type_name -> google.protobuf.Duration
	9,  // 25: grocer.jeagerx.RetryConfig.max_elapsed_time:type_name -> google.protobuf.Duration
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_grocer_jeagerx_config_proto_init() }
func file_grocer_jeagerx_config_proto_init() {
	if File_grocer_jeagerx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grocer_jeagerx_config_proto_rawDesc), len(file_grocer_jeagerx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grocer_jeagerx_config_proto_goTypes,
		DependencyIndexes: file_grocer_jeagerx_config_proto_depIdxs,
		MessageInfos:      file_grocer_jeagerx_config_proto_msgTypes,
	}.Build()
	File_grocer_jeagerx_config_proto = out.File
	file_grocer_jeagerx_config_proto_goTypes = nil
	file_grocer_jeagerx_config_proto_depIdxs = nil
}
